packages:
  - packages/*
minimumReleaseAgeExclude:
  - '@oxc-parser/binding-darwin-x64@0.152.0'
  - '@oxc-parser/binding-freebsd-x64@0.152.0'
  - '@oxc-parser/binding-linux-x64-gnu@0.152.0'
  - '@oxc-parser/binding-linux-x64-musl@0.152.0'
  - '@oxc-parser/binding-win32-x64-msvc@0.152.0'
  - oxc-parser@0.152.0
